"""empty message

Revision ID: 1ea29c48af8c
Revises: 8fc4c09589df
Create Date: 2023-05-16 15:26:34.538919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea29c48af8c'
down_revision = '8fc4c09589df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charity', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
