"""empty message

Revision ID: 8fc4c09589df
Revises: 32e796b84812
Create Date: 2023-05-15 08:04:44.938868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc4c09589df'
down_revision = '32e796b84812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.FLOAT(), nullable=True))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
